#ifndef __DISTANCES_H__
#define __DISTANCES_H__

//distances
#define MANHATTEN 0
#define SMIRNOFF 1
#define KOLMOGOROFF 2
#define LEMAN_ROSENBLATT 3
#define EUC 4
#define INTERSECT 5
#define CHI_SQUARE 6
#define KL 7
#define SYM_KL 8
#define JENSEN_SHANNON 9
#define HOMOGENEITY 10
#define SIMPLIFIED_HOMOGENEITY 11
#define PNN 12
#define MY_PNN 13
#define BHATTACHARYYA 14
#define LOCAL_DESCRIPTORS 15

//#define DISTANCE MANHATTEN
#define DISTANCE EUC
//#define DISTANCE INTERSECT
//#define DISTANCE SMIRNOFF
//#define DISTANCE KOLMOGOROFF
//#define DISTANCE LEMAN_ROSENBLATT
//#define DISTANCE CHI_SQUARE
//#define DISTANCE KL
//#define DISTANCE SYM_KL
//#define DISTANCE JENSEN_SHANNON
//#define DISTANCE HOMOGENEITY
//#define DISTANCE SIMPLIFIED_HOMOGENEITY
//#define DISTANCE PNN
//#define DISTANCE MY_PNN
//#define DISTANCE BHATTACHARYYA
//#define DISTANCE LOCAL_DESCRIPTORS

#endif //__DISTANCES_H__